module.exports = {
    /**
      - GUILD_CREATE
      - GUILD_UPDATE
      - GUILD_DELETE
      - GUILD_ROLE_CREATE
      - GUILD_ROLE_UPDATE
      - GUILD_ROLE_DELETE
      - CHANNEL_CREATE
      - CHANNEL_UPDATE
      - CHANNEL_DELETE
      - CHANNEL_PINS_UPDATE
      - THREAD_CREATE
      - THREAD_UPDATE
      - THREAD_DELETE
      - THREAD_LIST_SYNC
      - THREAD_MEMBER_UPDATE
      - THREAD_MEMBERS_UPDATE *
      - STAGE_INSTANCE_CREATE
      - STAGE_INSTANCE_UPDATE
      - STAGE_INSTANCE_DELETE
      */
    GUILDS: (1 << 0),
    /**
      - GUILD_MEMBER_ADD
      - GUILD_MEMBER_UPDATE
      - GUILD_MEMBER_REMOVE
      - THREAD_MEMBERS_UPDATE
    */
    GUILD_MEMBERS: (1 << 1),
    /**
      - GUILD_AUDIT_LOG_ENTRY_CREATE
      - GUILD_BAN_ADD
      - GUILD_BAN_REMOVE
      */
    GUILD_MODERATION: (1 << 2),
    /**
      - GUILD_EMOJIS_UPDATE
      - GUILD_STICKERS_UPDATE
      */
    GUILD_EMOJIS_AND_STICKERS: (1 << 3),
    /**
      - GUILD_INTEGRATIONS_UPDATE
      - INTEGRATION_CREATE
      - INTEGRATION_UPDATE
      - INTEGRATION_DELETE
      */
    GUILD_INTEGRATIONS: (1 << 4),
    /**
      - WEBHOOKS_UPDATE
     */
    GUILD_WEBHOOKS: (1 << 5),
    /**
      - INVITE_CREATE
      - INVITE_DELETE
      */
    GUILD_INVITES: (1 << 6),
    /**
      - VOICE_STATE_UPDATE
      */
    GUILD_VOICE_STATES: (1 << 7),
    /**
      - PRESENCE_UPDATE */
    GUILD_PRESENCES: (1 << 8),
    /**
      - MESSAGE_CREATE
      - MESSAGE_UPDATE
      - MESSAGE_DELETE
      - MESSAGE_DELETE_BULK
      */
    GUILD_MESSAGES: (1 << 9),
    /**
      - MESSAGE_REACTION_ADD
      - MESSAGE_REACTION_REMOVE
      - MESSAGE_REACTION_REMOVE_ALL
      - MESSAGE_REACTION_REMOVE_EMOJI
      */
    GUILD_MESSAGE_REACTIONS: (1 << 10),
    /**
      - TYPING_START
      */
    GUILD_MESSAGE_TYPING: (1 << 11),
    /**
      - MESSAGE_CREATE
      - MESSAGE_UPDATE
      - MESSAGE_DELETE
      - CHANNEL_PINS_UPDATE
      */
    DIRECT_MESSAGES: (1 << 12),
    /**
      - MESSAGE_REACTION_ADD
      - MESSAGE_REACTION_REMOVE
      - MESSAGE_REACTION_REMOVE_ALL
      - MESSAGE_REACTION_REMOVE_EMOJI
      */
    DIRECT_MESSAGE_REACTIONS: (1 << 13),
    /**
      - TYPING_START
      */
    DIRECT_MESSAGE_TYPING: (1 << 14),
    MESSAGE_CONTENT: (1 << 15),
    /**
      - GUILD_SCHEDULED_EVENT_CREATE
      - GUILD_SCHEDULED_EVENT_UPDATE
      - GUILD_SCHEDULED_EVENT_DELETE
      - GUILD_SCHEDULED_EVENT_USER_ADD
      - GUILD_SCHEDULED_EVENT_USER_REMOVE
      */
    GUILD_SCHEDULED_EVENTS: (1 << 16),
    /**
      - AUTO_MODERATION_RULE_CREATE
      - AUTO_MODERATION_RULE_UPDATE
      - AUTO_MODERATION_RULE_DELETE
      */
    AUTO_MODERATION_CONFIGURATION: (1 << 20),
    /**
      - AUTO_MODERATION_ACTION_EXECUTION
      */
    AUTO_MODERATION_EXECUTION: (1 << 21),
    /**
      - MESSAGE_POLL_VOTE_ADD
      - MESSAGE_POLL_VOTE_REMOVE
      */
    GUILD_MESSAGE_POLLS: (1 << 24),
    /**
      - MESSAGE_POLL_VOTE_ADD
      - MESSAGE_POLL_VOTE_REMOVE
      */
    DIRECT_MESSAGE_POLLS: (1 << 25)
};
